services:
  backend_meetup_like_prod:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - '3033:3033'
    environment:
      - PORT=3033
      - NODE_ENV=production
    volumes:
      - ./src:/app/src